kind: project
entrypoint: main.tsp
emit:
  - "@typespec/openapi3"
options:
  "@typespec/openapi3":
    emitter-output-dir: "{cwd}/dist"
    output-file: "foo-backend-openapi.yaml"
    openapi-versions:
      - "3.1.0"
